version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
